# Generated by Django 4.2.7 on 2023-11-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='background_picture',
            field=models.JSONField(blank=True, default={}),
        ),
    ]
