# Generated by Django 4.2.6 on 2023-10-18 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='image',
        ),
        migrations.AddField(
            model_name='activity',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
