# Generated by Django 4.2.7 on 2023-11-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background_picture',
            field=models.TextField(blank=True),
        ),
    ]
