# Generated by Django 4.2.6 on 2023-10-12 05:19

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 11, 5, 19, 17, 416763, tzinfo=datetime.timezone.utc), verbose_name='Date ended'),
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
    ]
