# Generated by Django 4.2.7 on 2023-11-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0002_user_background_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=22),
        ),
    ]
