# Generated by Django 4.2.6 on 2023-10-12 08:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0002_user_friends_alter_activity_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_date',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='activity_name',
        ),
        migrations.AddField(
            model_name='activity',
            name='background_picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 11, 8, 39, 52, 965171, tzinfo=datetime.timezone.utc), verbose_name='Date of Activity'),
        ),
        migrations.AddField(
            model_name='activity',
            name='full_description',
            field=models.TextField(blank=True, verbose_name='Full Description'),
        ),
        migrations.AddField(
            model_name='activity',
            name='picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='activity',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 11, 8, 39, 52, 965171, tzinfo=datetime.timezone.utc), verbose_name='Date ended'),
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], max_length=10)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
