# Generated by Django 4.2.6 on 2023-10-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0002_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='background_picture',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='activity',
            name='picture',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.TextField(blank=True, max_length=100000),
        ),
    ]
