# Generated by Django 4.2.6 on 2023-10-10 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0002_tag_activity_activity_date_activity_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='place',
            field=models.CharField(blank=True, max_length=200, verbose_name='Place'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 9, 6, 18, 22, 808065, tzinfo=datetime.timezone.utc), verbose_name='Date ended'),
        ),
    ]
