# Generated by Django 4.2.6 on 2023-10-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0002_alter_activity_background_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='activity',
            name='last_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last date of activity'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Application Deadline'),
        ),
    ]
