# Generated by Django 4.2.6 on 2023-10-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0002_remove_activity_image_activity_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(blank=True),
        ),
    ]
