# Generated by Django 4.2.7 on 2023-11-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0003_alter_activity_background_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='background_picture',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
