# Generated by Django 4.2.6 on 2023-10-30 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0003_rename_date_activity_start_date_activity_last_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
