# Generated by Django 4.2.6 on 2023-10-12 09:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0003_remove_activity_activity_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='participation_limit',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 11, 9, 13, 2, 291353, tzinfo=datetime.timezone.utc), verbose_name='Date of Activity'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 11, 9, 13, 2, 291353, tzinfo=datetime.timezone.utc), verbose_name='Date ended'),
        ),
    ]
