# Generated by Django 4.2.6 on 2023-10-30 04:06

import action.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0004_alter_activity_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='end_date',
            field=models.DateTimeField(default=action.models.default_end_date, null=True, verbose_name='Application Deadline'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='last_date',
            field=models.DateTimeField(default=action.models.default_last_date, null=True, verbose_name='Last date of activity'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_date',
            field=models.DateTimeField(default=action.models.default_start_date, null=True, verbose_name='Date of Activity'),
        ),
    ]
