# Generated by Django 4.2.6 on 2023-10-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0004_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(default='https://firebasestorage.googleapis.com/v0/b/ku-active-401915.appspot.com/o/default.jpg?alt=media&token=fedfb21e-7bee-4ac4-ba', max_length=500),
        ),
    ]
