# Generated by Django 4.2.6 on 2023-10-12 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0004_activity_participation_limit_alter_activity_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='participation_limit',
            new_name='participant_limit',
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 11, 9, 47, 46, 222142, tzinfo=datetime.timezone.utc), verbose_name='Date of Activity'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 11, 9, 47, 46, 222142, tzinfo=datetime.timezone.utc), verbose_name='Date ended'),
        ),
    ]
