# Generated by Django 4.2.6 on 2023-11-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0004_rename_tag_category_rename_tags_activity_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='full_description',
            field=models.TextField(blank=True, null=True, verbose_name='Full Description'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='place',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Place'),
        ),
    ]
