# Generated by Django 4.2.6 on 2023-10-30 04:08

import action.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0005_alter_activity_end_date_alter_activity_last_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='end_date',
            field=models.DateTimeField( verbose_name='Application Deadline'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='last_date',
            field=models.DateTimeField( verbose_name='Last date of activity'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_date',
            field=models.DateTimeField( verbose_name='Date of Activity'),
        ),
    ]
