# Generated by Django 4.2.6 on 2023-10-20 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0005_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='background_picture',
            field=models.URLField(default='https://firebasestorage.googleapis.com/v0/b/ku-active-401915.appspot.com/o/Profile_picture%2Fdefault.jpg?alt=media&token=7c6aba43-2264-4b04-a1a3-52c040a82b9b&_gl=1*mn5amf*_ga*MTEyNjQxMzEwNy4xNjk2Nzc3OTM4*_ga_CW55HF8NVT*MTY5Nzc3MjYzOC43LjEuMTY5Nzc3Mjc5MS4zNC4wLjA.', max_length=500),
        ),
        migrations.AlterField(
            model_name='activity',
            name='picture',
            field=models.URLField(default='https://firebasestorage.googleapis.com/v0/b/ku-active-401915.appspot.com/o/Profile_picture%2Fdefault.jpg?alt=media&token=7c6aba43-2264-4b04-a1a3-52c040a82b9b&_gl=1*mn5amf*_ga*MTEyNjQxMzEwNy4xNjk2Nzc3OTM4*_ga_CW55HF8NVT*MTY5Nzc3MjYzOC43LjEuMTY5Nzc3Mjc5MS4zNC4wLjA.', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(default='https://firebasestorage.googleapis.com/v0/b/ku-active-401915.appspot.com/o/Profile_picture%2Fdefault.jpg?alt=media&token=7c6aba43-2264-4b04-a1a3-52c040a82b9b&_gl=1*mn5amf*_ga*MTEyNjQxMzEwNy4xNjk2Nzc3OTM4*_ga_CW55HF8NVT*MTY5Nzc3MjYzOC43LjEuMTY5Nzc3Mjc5MS4zNC4wLjA.', max_length=500),
        ),
    ]
