# Generated by Django 4.2.7 on 2023-12-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0005_alter_activity_full_description_alter_activity_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendstatus',
            name='request_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted')], default=None, max_length=50, null=True),
        ),
    ]
