# Generated by Django 4.2.6 on 2023-10-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0007_rename_date_activity_activity_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='background_picture',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='activity',
            name='picture',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(default='', max_length=500),
        ),
    ]
