# Generated by Django 4.2.7 on 2023-11-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0008_user_event_encoder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='event_encoder',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
