# Generated by Django 4.2.6 on 2023-10-13 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0008_friendstatus_alter_activity_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 12, 10, 32, 5, 198163, tzinfo=datetime.timezone.utc), verbose_name='Date of Activity'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 12, 10, 32, 5, 198163, tzinfo=datetime.timezone.utc), verbose_name='Date ended'),
        ),
        migrations.AlterField(
            model_name='friendstatus',
            name='request_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Declined', 'Declined')], default=None, max_length=50, null=True),
        ),
    ]
