# Generated by Django 4.2.6 on 2023-10-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0008_alter_activity_background_picture_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='activity_date',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='activity',
            name='background_picture',
            field=models.URLField(blank=True, default='https://firebasestorage.googleapis.com/v0/b/ku-active-401915.appspot.com/o/Activity_background_picture%2Fdefault_background.jpg?alt=media&token=bc2b4b66-56a0-4c74-9668-ed66843bd31e&_gl=1*bwzi1t*_ga*MTEyNjQxMzEwNy4xNjk2Nzc3OTM4*_ga_CW55HF8NVT*MTY5Nzg5NDM0OS4xNC4xLjE2OTc4OTUzODQuNTcuMC4w', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.URLField(default='https://firebasestorage.googleapis.com/v0/b/ku-active-401915.appspot.com/o/Profile_picture%2Fdefault.jpg?alt=media&token=7c6aba43-2264-4b04-a1a3-52c040a82b9b&_gl=1*w81pai*_ga*MTEyNjQxMzEwNy4xNjk2Nzc3OTM4*_ga_CW55HF8NVT*MTY5Nzg5NDM0OS4xNC4xLjE2OTc4OTUyNjEuNTAuMC4w', max_length=500),
        ),
    ]
