from .activity_edit_view import *
from .edit_profile_view import *
from .activity import *
from .index_view import *
from .friend_status import *
from .detail_view import *
from .friend_view import *
from .activity_create_view import *
from .activity_manage_view import *
from .profile_view import *
from .calendar_view import *
