from .ActivityEditView import *
from .EditProfileView import *
from .Activity import *
from .IndexView import *
from .FriendStatus import *
from .DetailView import *
from .FriendView import *
from .ActivityCreateView import *
from .ActivityManageView import *
from .ProfileView import *
